version: '3.4'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/app
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7-fpm
        volumes:
            - ./app:/var/app
